# H2 база данных в памяти
spring.datasource.url=jdbc:h2:mem:garden_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 консоль для удобства
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA настройки
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# data.sql будет выполняться всегда
spring.sql.init.mode=always